### ISSUE TITLE
Hover container ul styles

### ISSUE THREAD

**Issue by seanwash** [ShaRay/strict#7]
For the most part this looks good! One thing though, the ul wrapping those two icons has margin and padding on it http://d.pr/i/s3Rx/1XMBIirJ

Also, you'd want to remove the `cursor: pointer` style from `.content` inside the hover container. When I hover over the image the whole thing is the pointer, which is sort of confusing. Ideally you'd just want the icon boxes to show the pointer on hover. Also, since they're both links so you want to make sure there's an a tag in there

**Comment by ShaRay** [comment]
I used position absolute on icons and position relative on container so I was able to take off the margins and positioned the icons using top and right. 

removed cursor: pointer 

Added a tags on preview and link icons
